"""Add role column to users table

Revision ID: b649112c08a3
Revises: 29365ecfe46e
Create Date: 2025-12-03 20:17:13.875402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b649112c08a3'
down_revision: Union[str, Sequence[str], None] = '29365ecfe46e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    userrole_enum = sa.Enum('ADMIN', 'USER', name='userrole')
    userrole_enum.create(op.get_bind(), checkfirst=True)

    # Add column with server_default for existing rows
    op.add_column('users', sa.Column('role', userrole_enum, nullable=False, server_default='USER'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # Drop the enum type
    userrole_enum = sa.Enum('ADMIN', 'USER', name='userrole')
    userrole_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
